export const MOVIES_LOADING = "MOVIES_LOADING";
export const MOVIES_LOAD_SUCCESS = "MOVIES_LOAD_SUCCESS";
export const MOVIES_LOAD_FAIL = "MOVIES_LOAD_FAIL";
export const MOVIE_DETAILS_LOADING = "MOVIE_DETAILS_LOADING";
export const MOVIE_DETAILS_LOAD_SUCCESS = "MOVIE_DETAILS_LOAD_SUCCESS";
export const MOVIE_DETAILS_LOAD_FAIL = "MOVIE_DETAILS_LOAD_FAIL";
